apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-one
  namespace: part-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-one 
  template:
    metadata:
      labels:
        app: app-one
    spec:
      containers:
      - name: hello-kubernetes-container
        image: paulbouwer/hello-kubernetes:1.10
        ports:
        - containerPort: 8080
        env:
          - name: MESSAGE
            value: "Hello from app1"
            
          - name: KUBERNETES_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: KUBERNETES_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace