
Vagrant.configure("2") do |config|
  config.vm.boot_timeout = 800
  config.vm.define "amounadiS" do |control|
    control.vm.box = "bento/ubuntu-22.04"
    control.vm.hostname= "amounadiS"
    control.vm.network "private_network", ip: "192.168.56.110"
    control.vm.provider "virtualbox" do |vb|
      vb.cpus = 2
      vb.memory = "2048"
    end
  end
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbooks/deploy.yml" 
  end
end

