
Vagrant.configure("2") do |config|
  config.vm.boot_timeout = 600
  config.vm.define "amounadiS" do |control|
    control.vm.box = "bento/ubuntu-22.04"
    control.vm.hostname= "amounadiS"
    control.vm.network "private_network", ip: "192.168.56.110"
    control.vm.provider "virtualbox" do |vb|
      vb.cpus = 1
      vb.memory = "1024"
    end
    control.vm.provision "shell", inline: <<-SHELL
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --node-ip=192.168.56.110 --tls-san=192.168.56.110" sh -
      sudo cat /var/lib/rancher/k3s/server/node-token > /vagrant/node-token
    SHELL
  end

  config.vm.define "amounadiSW" do |control|
    control.vm.box = "bento/ubuntu-22.04"
    control.vm.hostname= "amounadiSW"
    control.vm.network "private_network", ip: "192.168.56.111"
    control.vm.provider "virtualbox" do |vb|
      vb.cpus = 1
      vb.memory = "1024"
    end
    control.vm.provision "shell", inline: <<-SHELL
      export K3S_URL="https://192.168.56.110:6443"
      export K3S_TOKEN=$(cat /vagrant/node-token)
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="agent --node-ip=192.168.56.111" K3S_URL=$K3S_URL K3S_TOKEN=$K3S_TOKEN sh -
    SHELL
  end
end

